<!-- HEAD --> 
<?php
 ?>

<!DOCTYPE HTML>
<html lang="nl">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<meta charset="utf-8">

	<!--Let browser know website is optimized for mobile-->
	<meta name="viewport" content="width=device-width, initial-scale=1">

	<!--Import Google Icon Font-->
      <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
      <!--Import materialize.css-->
      


	<!-- STYLESHEETS -->
	<link type="text/css" rel="stylesheet" href="<?php echo DIR_MATERIALIZE ?>/css/materialize.min.css"  media="screen,projection"/>
	<link rel="stylesheet" href="<?php echo DIR_SKIN . '/css/styles.css';?>">
	<link rel="stylesheet" href="<?php echo DIR_SKIN . '/css/mediaqueries.css';?>">
	<script type="text/javascript" src="<?php echo DIR_MATERIALIZE . '/js/jquery-3.1.1.min.js'?>"></script>
</head>