<!-- HEAD --> 
<?php
 ?>

<!DOCTYPE HTML>
<html lang="nl">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta charset="utf-8">

	<!-- STYLESHEETS -->
	<link rel="stylesheet" href="<?php echo DIR_BOOTSTRAP . '/css/bootstrap.min.css';?>">
	<link rel="stylesheet" href="<?php echo DIR_BOOTSTRAP . '/css/bootstrap-theme.min.css';?>">
	<link rel="stylesheet" href="<?php echo DIR_SKIN . '/css/styles.css';?>">
	<link rel="stylesheet" href="<?php echo DIR_SKIN . '/css/mediaqueries.css';?>">
	<script type="text/javascript" src="<?php echo DIR_BOOTSTRAP . '/js/jquery-3.1.1.min.js'?>"></script>
</head>