<!-- TOP LINKS -->
<?php
 ?>

<body>
<div class="container-fluid center-align maincolor top-link-container valign-wrapper">
	<div class="container valign">
		<div class="row no-mgbottom">
			<div class="col s6 left-align">
			<a class="top-links" href="#">Over ons</a>
			</div>
			<div class="col s6 right-align">
			<a class="top-links" href="#">Inloggen</a>
			<a class="top-links" href="#">Registreren</a>
			</div>
		</div>
	</div>
</div>