<!-- TOP LINKS -->
<?php
 ?>

<body>
<div class="container-fluid center-align main-color top-link-container valign-wrapper">
	<div class="container valign">
		<div class="row no-mgbottom valign-wrapper">
			<div class="col s6 left-align accent-color-1 valign rel">
				<form><input type="text" placeholder="Zoek naar vrienden" /> <i class="material-icons search-icon">search</i></form>
			</div>
			<div class="col s6 right-align valign rel">
				<a class="top-links" href="#"><i class="material-icons">perm_identity</i>Inloggen</a>
				<a class="top-links" href="#"><i class="material-icons">mode_edit</i>Registreren</a>
			</div>
		</div>
	</div>
</div>